### PR TITLE
Update of the README.md for Alpha 3

### PR DESCRIPTION
**Pull request by televisionia**
Nothing big, just did some easy work for you.
- Made it so that it says now 4 players can support the script
- Made sure to mention battles are not supported yet
- Mentioned that trades are now possible

### CODE REVIEW

**Comment by SWHSmash** [comment]
maybe add a future support for all gen 3 games as well, so that this is also answered. (see [#15](https://github.com/TheHunterManX/GBA-PK-multiplayer/issues/15) at issues) :)

**Comment by televisionia** [comment]
> maybe add a hint for future support for all gen 3 games as well, so that this is also answered. (see [#15](https://github.com/TheHunterManX/GBA-PK-multiplayer/issues/15) at issues) :)

@SWHSmash  This is already mentioned in the original description, and hasn't been removed in the new commits, but I think you do have somewhat of a point, it should be made a bit more clearer. Will change!

**Comment by SWHSmash** [comment]
> This is already mentioned in the original description

I know that, but some people still ask for it. :P
Okay :)

**Comment by televisionia** [comment]
> > This is already mentioned in the original description
> 
> I know that, but some people still ask for it. :P Okay :)

@SWHSmash If you want to get the attention of the repository author try submitting a review to the pull request

**Comment by televisionia** [comment]
Uh oh, instead of merging the pull request he just copy and pasted the description. Which is fine, but now I inconveniently have to remove this pull request.

**Comment by televisionia** [comment]
The creator just changed the description, well, I don't think he noticed there was a pull request here either, so I'm going to close this as it is now not needed anymore.

**Comment by televisionia** [comment]
Closed because the description on the main repository changed, making the entire point of this pull request outdated.

**Pull request closed without merging**
